### ISSUE TITLE
Change config value

### ISSUE THREAD

**Issue by Anarasty** [OleksiiNikitenko/TPRS_Lab_4#1]
DEAR @OleksiiNikitenko, in your file config.py I found one issue. Please, setup the value of representative_portion according to design, It's value supose to be 1000 but not 5000. 

https://github.com/OleksiiNikitenko/TPRS_Lab_4/blob/602ee644dff501d23d45fc5dbb5dc5d336489501/lab_4_trps/src/config.py#L5

**Comment by OleksiiNikitenko** [comment]
Hi @Anarasty,
Thank you for your code review. I will change my impimentation.

**Comment by OleksiiNikitenko** [comment]
Hi @Anarasty,
Please check my resent changes. Thank you.

**Comment by Anarasty** [comment]
@OleksiiNikitenko I see. Everything is fine, good job!
